map <F5> :GoDebugStart <Enter>
map <F9> :GoDebugBreakpoint <Enter>
map <F10> :GoDebugStepOut <Enter>
map <F11> :GoDebugStep <Enter>
map <F12> :GoDef <Enter>
map <C-Left> :GoDefPop <Enter>
map <C-Right> :GoDefStack <Enter>
map <C-F12> :GoCallers <Enter>
map <S-F12> :GoCallers <Enter>
